## Numpy

###NumPy Array

In [1]:
listy = [1,2,3]

In [2]:
listy

[1, 2, 3]

In [6]:
#casting a normal python list into an array
import numpy as np
np.array(listy)

array([1, 2, 3])

In [7]:
mat =[[1,2,3],[4,6,8],[3,7,5]]

In [8]:
#casting a matrix into an array
import numpy as np
np.array(mat)

array([[1, 2, 3],
       [4, 6, 8],
       [3, 7, 5]])

In [10]:
#creating an array
my_arr = np.arange(0,10)

In [11]:
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
my_arr_even = np.arange(0,10,2)

In [13]:
my_arr_even

array([0, 2, 4, 6, 8])

In [20]:
#create an array of zeros
zerosbaby = np.zeros(3)
#create an array of ones
onesbaby = np.ones(3)

In [24]:
zerosbaby

array([0., 0., 0.])

In [122]:
onesbaby

array([1., 1., 1.])

In [123]:
#create an array of 10 fives
array_5 = np.ones(10) * 5
array_5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [28]:
#create a matrix of zeros
zerosmat = np.zeros((5,5))
#create a matrix of ones
onesmat = np.ones((3,4))

In [29]:
zerosmat

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [30]:
onesmat

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [31]:
np.linspace(0,10,20) # 2O even-spaced numbers from 0 to 10

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [32]:
np.eye(4) #identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [36]:
#creating random arrays
np.random.rand(6) #returns an array of 6 random nb ( centered around 1)

array([0.67971574, 0.46298506, 0.58854642, 0.8802649 , 0.24661604,
       0.62159809])

In [37]:
np.random.randn(6) # 6 random nb centered around 0

array([ 0.02207317, -0.50218467,  0.09337526,  0.18665995, -0.1775248 ,
       -0.87296595])

In [40]:
np.random.randint(1,100,10)  #10 random numbers from 1 inc to 100 ( not including 100)

array([83, 36, 51, 99, 45, 12, 45, 46, 45, 59])

In [41]:
my_arr = np.arange(0,50)

In [42]:
my_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [47]:
my_arr.reshape(5,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [53]:
random_arr = np.random.randint(0,100,10)

In [54]:
random_arr

array([ 0, 64, 91, 82, 98, 37, 96, 53, 84, 45])

In [58]:
random_arr.max()

98

In [59]:
random_arr.argmax()

4

In [57]:
random_arr.min()

0

In [60]:
random_arr.argmin()

0

In [62]:
random_arr.shape #check the shape of an array

(10,)

In [63]:
random_arr.dtype # returns type of objects in an array

dtype('int32')

### Numpy indexing and selection

In [66]:
import numpy as np
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
arr[8] #return the value at index 8

8

In [71]:
arr[0:5] # returns the values from index 0 to 5

array([0, 1, 2, 3, 4])

In [73]:
arr[5:] #grabs everything beyond index 5

array([ 5,  6,  7,  8,  9, 10])

In [75]:
arr [0:5] = 110
arr

array([110, 110, 110, 110, 110,   5,   6,   7,   8,   9,  10])

In [81]:
arr = np.arange (0,11)

In [82]:
#be careful !
#slicing an array does not create a copy of the array 
slice_of_arr = arr[0:5]
slice_of_arr

array([0, 1, 2, 3, 4])

In [86]:
slice_of_arr[0:3] = 99
slice_of_arr

array([99, 99, 99,  3,  4])

In [87]:
arr  # Changes are also reflected here !

array([99, 99, 99,  3,  4,  5,  6,  7,  8,  9, 10])

In [88]:
#to copy an array 
arr_copy = arr.copy()
arr_copy

array([99, 99, 99,  3,  4,  5,  6,  7,  8,  9, 10])

In [90]:
#grabing content from a matrix
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [92]:
arr_2d[0][0]

5

In [93]:
arr_2d[0]

array([ 5, 10, 15])

In [94]:
arr_2d[2,1]

40

In [96]:
arr_2d [1,1]

25

In [103]:
arr_2d[:,1:]

array([[10, 15],
       [25, 30],
       [40, 45]])

In [104]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [105]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [106]:
#grabbing the last 2 lines 
arr_2d [1:,:]

array([[20, 25, 30],
       [35, 40, 45]])

In [107]:
#Conditional Selection
arr_boo = np.arange(0,11)

In [111]:
bool_arr = arr_boo > 5 # will return an array of boolean values
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [112]:
arr_boo[bool_arr] # will return the values where the boolean was True !

array([ 6,  7,  8,  9, 10])

In [113]:
#doing it all in one step : 
arr_boo [arr_boo >5]

array([ 6,  7,  8,  9, 10])

In [114]:
#Numpy Operations
import numpy as np
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [115]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [116]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [118]:
arr + 100 # adds 100 to every element

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [119]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [125]:
np.max(arr)

10

In [127]:
mat = np.arange(1,26).reshape(5,5)
mat
mat.sum(axis=0) #get sumof all columns in a matrix

array([55, 60, 65, 70, 75])

reference : https://docs.scipy.org/doc/numpy-1.15.1/reference/ufuncs.html 

### Pandas

In [129]:
import numpy as np
import pandas as pd
labels = ['a','b','c']
my_data = [10,20,30]
arr = np.array(my_data)
d = {'a':10,'b':20,'c':30}

In [130]:
pd.Series(data = my_data)

0    10
1    20
2    30
dtype: int64

In [132]:
pd.Series(data = my_data,index =  labels)

a    10
b    20
c    30
dtype: int64

In [133]:
pd.Series(my_data,labels) # creating a series from 2 lists

a    10
b    20
c    30
dtype: int64

In [134]:
pd.Series(arr,labels) #creating a series from an array

a    10
b    20
c    30
dtype: int32

In [135]:
pd.Series(d) #creating a series from a dictionary 

a    10
b    20
c    30
dtype: int64

In [137]:
ser1 = pd.Series([1,2,3,4],['USA','Germany','France','Belgium'])
ser1

USA        1
Germany    2
France     3
Belgium    4
dtype: int64

In [140]:
ser2 = pd.Series([1,2,5,4],['USA','Germany','Italy','Belgium'])
ser2

USA        1
Germany    2
Italy      5
Belgium    4
dtype: int64

In [142]:
ser1['USA']

1

In [143]:
ser1 + ser2

Belgium    8.0
France     NaN
Germany    4.0
Italy      NaN
USA        2.0
dtype: float64

### Pandas - Dataframes

In [145]:
import numpy as np
import pandas as pd
from numpy.random import randn

In [146]:
np.random.seed(101)

In [149]:
df = pd.DataFrame(randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])

In [150]:
df

W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [165]:
#select a column from the dataframe
df['W'] #return a series from the df object

A    0.302665
B   -0.134841
C    0.807706
D   -0.497104
E   -0.116773
Name: W, dtype: float64

In [153]:
df.W

A    0.302665
B   -0.134841
C    0.807706
D   -0.497104
E   -0.116773
Name: W, dtype: float64

In [156]:
df[['W','Z']]

W         Z
A  0.302665 -1.159119
B -0.134841  0.184502
C  0.807706  0.329646
D -0.497104  0.484752
E -0.116773  1.996652

In [158]:
df['new'] = df['W'] + df['Z']
df.new

A   -0.856454
B    0.049661
C    1.137352
D   -0.012352
E    1.879879
Name: new, dtype: float64

In [159]:
df

W         X         Y         Z       new
A  0.302665  1.693723 -1.706086 -1.159119 -0.856454
B -0.134841  0.390528  0.166905  0.184502  0.049661
C  0.807706  0.072960  0.638787  0.329646  1.137352
D -0.497104 -0.754070 -0.943406  0.484752 -0.012352
E -0.116773  1.901755  0.238127  1.996652  1.879879

In [160]:
#drop a column
df.drop('new',axis = 1)

W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [161]:
df  # not affecting the original df

W         X         Y         Z       new
A  0.302665  1.693723 -1.706086 -1.159119 -0.856454
B -0.134841  0.390528  0.166905  0.184502  0.049661
C  0.807706  0.072960  0.638787  0.329646  1.137352
D -0.497104 -0.754070 -0.943406  0.484752 -0.012352
E -0.116773  1.901755  0.238127  1.996652  1.879879

In [163]:
# to actually drop it from the df
df.drop('new',axis=1,inplace=True)

In [164]:
df

W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [167]:
#Select a row
df.loc['A'] #returns the row with Label A

W    0.302665
X    1.693723
Y   -1.706086
Z   -1.159119
Name: A, dtype: float64

In [169]:
df.iloc[0] #using the index of the row

W    0.302665
X    1.693723
Y   -1.706086
Z   -1.159119
Name: A, dtype: float64

In [171]:
df.loc['B','Y'] #value at row B , column Y

0.16690463609281317

In [174]:
df.loc[['B','D'],['W','Z']]

W         Z
B -0.134841  0.184502
D -0.497104  0.484752

In [175]:
df > 0

W      X      Y      Z
A   True   True  False  False
B  False   True   True   True
C   True   True   True   True
D  False  False  False   True
E  False   True   True   True

In [176]:
df[df>0] #values where the condition is true

W         X         Y         Z
A  0.302665  1.693723       NaN       NaN
B       NaN  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D       NaN       NaN       NaN  0.484752
E       NaN  1.901755  0.238127  1.996652

In [177]:
df

W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [178]:
df['W'] > 0

A     True
B    False
C     True
D    False
E    False
Name: W, dtype: bool

In [181]:
df[df['W']> 0] #returns all the rows where df['W'] > 0

W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
C  0.807706  0.072960  0.638787  0.329646

In [182]:
df[df['Z']> 0]

W         X         Y         Z
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [183]:
df[df['Z']> 0]['Y'] #returns the Y column for the rows where df['Z']>0

B    0.166905
C    0.638787
D   -0.943406
E    0.238127
Name: Y, dtype: float64

In [185]:
df[df['Z']> 0] [['Y','X']]

Y         X
B  0.166905  0.390528
C  0.638787  0.072960
D -0.943406 -0.754070
E  0.238127  1.901755

In [187]:
#Passing in multiple conditions
df [ (df['Z']>0) & (df['X']>0)] #use & and not and !

W         X         Y         Z
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
E -0.116773  1.901755  0.238127  1.996652

In [191]:
df [ (df['Z']>0) | (df['X']>0)] #use | and not and !

W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [192]:
df.reset_index() #does not occur in place

index         W         X         Y         Z
0     A  0.302665  1.693723 -1.706086 -1.159119
1     B -0.134841  0.390528  0.166905  0.184502
2     C  0.807706  0.072960  0.638787  0.329646
3     D -0.497104 -0.754070 -0.943406  0.484752
4     E -0.116773  1.901755  0.238127  1.996652

In [194]:
newind = 'FR DE GB IT PL'.split()
newind

['FR', 'DE', 'GB', 'IT', 'PL']

In [202]:
df['countries'] = newind
df

W         X         Y         Z countries
A  0.302665  1.693723 -1.706086 -1.159119        FR
B -0.134841  0.390528  0.166905  0.184502        DE
C  0.807706  0.072960  0.638787  0.329646        GB
D -0.497104 -0.754070 -0.943406  0.484752        IT
E -0.116773  1.901755  0.238127  1.996652        PL

In [203]:
df.set_index('countries')

W         X         Y         Z
countries                                        
FR         0.302665  1.693723 -1.706086 -1.159119
DE        -0.134841  0.390528  0.166905  0.184502
GB         0.807706  0.072960  0.638787  0.329646
IT        -0.497104 -0.754070 -0.943406  0.484752
PL        -0.116773  1.901755  0.238127  1.996652