## Numpy

###NumPy Array

In [1]:
listy = [1,2,3]

In [2]:
listy

[1, 2, 3]

In [6]:
#casting a normal python list into an array
import numpy as np
np.array(listy)

array([1, 2, 3])

In [7]:
mat =[[1,2,3],[4,6,8],[3,7,5]]

In [8]:
#casting a matrix into an array
import numpy as np
np.array(mat)

array([[1, 2, 3],
       [4, 6, 8],
       [3, 7, 5]])

In [10]:
#creating an array
my_arr = np.arange(0,10)

In [11]:
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
my_arr_even = np.arange(0,10,2)

In [13]:
my_arr_even

array([0, 2, 4, 6, 8])

In [20]:
#create an array of zeros
zerosbaby = np.zeros(3)
#create an array of ones
onesbaby = np.ones(3)

In [24]:
zerosbaby

array([0., 0., 0.])

In [122]:
onesbaby

array([1., 1., 1.])

In [123]:
#create an array of 10 fives
array_5 = np.ones(10) * 5
array_5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [28]:
#create a matrix of zeros
zerosmat = np.zeros((5,5))
#create a matrix of ones
onesmat = np.ones((3,4))

In [29]:
zerosmat

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [30]:
onesmat

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [31]:
np.linspace(0,10,20) # 2O even-spaced numbers from 0 to 10

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [32]:
np.eye(4) #identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [36]:
#creating random arrays
np.random.rand(6) #returns an array of 6 random nb ( centered around 1)

array([0.67971574, 0.46298506, 0.58854642, 0.8802649 , 0.24661604,
       0.62159809])

In [37]:
np.random.randn(6) # 6 random nb centered around 0

array([ 0.02207317, -0.50218467,  0.09337526,  0.18665995, -0.1775248 ,
       -0.87296595])

In [40]:
np.random.randint(1,100,10)  #10 random numbers from 1 inc to 100 ( not including 100)

array([83, 36, 51, 99, 45, 12, 45, 46, 45, 59])

In [41]:
my_arr = np.arange(0,50)

In [42]:
my_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [47]:
my_arr.reshape(5,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [53]:
random_arr = np.random.randint(0,100,10)

In [54]:
random_arr

array([ 0, 64, 91, 82, 98, 37, 96, 53, 84, 45])

In [58]:
random_arr.max()

98

In [59]:
random_arr.argmax()

4

In [57]:
random_arr.min()

0

In [60]:
random_arr.argmin()

0

In [62]:
random_arr.shape #check the shape of an array

(10,)

In [63]:
random_arr.dtype # returns type of objects in an array

dtype('int32')

### Numpy indexing and selection

In [66]:
import numpy as np
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
arr[8] #return the value at index 8

8

In [71]:
arr[0:5] # returns the values from index 0 to 5

array([0, 1, 2, 3, 4])

In [73]:
arr[5:] #grabs everything beyond index 5

array([ 5,  6,  7,  8,  9, 10])

In [75]:
arr [0:5] = 110
arr

array([110, 110, 110, 110, 110,   5,   6,   7,   8,   9,  10])

In [81]:
arr = np.arange (0,11)

In [82]:
#be careful !
#slicing an array does not create a copy of the array 
slice_of_arr = arr[0:5]
slice_of_arr

array([0, 1, 2, 3, 4])

In [86]:
slice_of_arr[0:3] = 99
slice_of_arr

array([99, 99, 99,  3,  4])

In [87]:
arr  # Changes are also reflected here !

array([99, 99, 99,  3,  4,  5,  6,  7,  8,  9, 10])

In [88]:
#to copy an array 
arr_copy = arr.copy()
arr_copy

array([99, 99, 99,  3,  4,  5,  6,  7,  8,  9, 10])

In [90]:
#grabing content from a matrix
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [92]:
arr_2d[0][0]

5

In [93]:
arr_2d[0]

array([ 5, 10, 15])

In [94]:
arr_2d[2,1]

40

In [96]:
arr_2d [1,1]

25

In [103]:
arr_2d[:,1:]

array([[10, 15],
       [25, 30],
       [40, 45]])

In [104]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [105]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [106]:
#grabbing the last 2 lines 
arr_2d [1:,:]

array([[20, 25, 30],
       [35, 40, 45]])

In [107]:
#Conditional Selection
arr_boo = np.arange(0,11)

In [111]:
bool_arr = arr_boo > 5 # will return an array of boolean values
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [112]:
arr_boo[bool_arr] # will return the values where the boolean was True !

array([ 6,  7,  8,  9, 10])

In [113]:
#doing it all in one step : 
arr_boo [arr_boo >5]

array([ 6,  7,  8,  9, 10])

In [114]:
#Numpy Operations
import numpy as np
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [115]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [116]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [118]:
arr + 100 # adds 100 to every element

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [119]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [125]:
np.max(arr)

10

In [127]:
mat = np.arange(1,26).reshape(5,5)
mat
mat.sum(axis=0) #get sumof all columns in a matrix

array([55, 60, 65, 70, 75])

reference : https://docs.scipy.org/doc/numpy-1.15.1/reference/ufuncs.html 

### Pandas

In [129]:
import numpy as np
import pandas as pd
labels = ['a','b','c']
my_data = [10,20,30]
arr = np.array(my_data)
d = {'a':10,'b':20,'c':30}

In [130]:
pd.Series(data = my_data)

0    10
1    20
2    30
dtype: int64

In [132]:
pd.Series(data = my_data,index =  labels)

a    10
b    20
c    30
dtype: int64

In [133]:
pd.Series(my_data,labels) # creating a series from 2 lists

a    10
b    20
c    30
dtype: int64

In [134]:
pd.Series(arr,labels) #creating a series from an array

a    10
b    20
c    30
dtype: int32

In [135]:
pd.Series(d) #creating a series from a dictionary 

a    10
b    20
c    30
dtype: int64

In [137]:
ser1 = pd.Series([1,2,3,4],['USA','Germany','France','Belgium'])
ser1

USA        1
Germany    2
France     3
Belgium    4
dtype: int64

In [140]:
ser2 = pd.Series([1,2,5,4],['USA','Germany','Italy','Belgium'])
ser2

USA        1
Germany    2
Italy      5
Belgium    4
dtype: int64

In [142]:
ser1['USA']

1

In [143]:
ser1 + ser2

Belgium    8.0
France     NaN
Germany    4.0
Italy      NaN
USA        2.0
dtype: float64

### Pandas - Dataframes

In [145]:
import numpy as np
import pandas as pd
from numpy.random import randn

In [146]:
np.random.seed(101)

In [149]:
df = pd.DataFrame(randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])

In [150]:
df

W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [165]:
#select a column from the dataframe
df['W'] #return a series from the df object

A    0.302665
B   -0.134841
C    0.807706
D   -0.497104
E   -0.116773
Name: W, dtype: float64

In [153]:
df.W

A    0.302665
B   -0.134841
C    0.807706
D   -0.497104
E   -0.116773
Name: W, dtype: float64

In [156]:
df[['W','Z']]

W         Z
A  0.302665 -1.159119
B -0.134841  0.184502
C  0.807706  0.329646
D -0.497104  0.484752
E -0.116773  1.996652

In [158]:
df['new'] = df['W'] + df['Z']
df.new

A   -0.856454
B    0.049661
C    1.137352
D   -0.012352
E    1.879879
Name: new, dtype: float64

In [159]:
df

W         X         Y         Z       new
A  0.302665  1.693723 -1.706086 -1.159119 -0.856454
B -0.134841  0.390528  0.166905  0.184502  0.049661
C  0.807706  0.072960  0.638787  0.329646  1.137352
D -0.497104 -0.754070 -0.943406  0.484752 -0.012352
E -0.116773  1.901755  0.238127  1.996652  1.879879

In [160]:
#drop a column
df.drop('new',axis = 1)

W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [161]:
df  # not affecting the original df

W         X         Y         Z       new
A  0.302665  1.693723 -1.706086 -1.159119 -0.856454
B -0.134841  0.390528  0.166905  0.184502  0.049661
C  0.807706  0.072960  0.638787  0.329646  1.137352
D -0.497104 -0.754070 -0.943406  0.484752 -0.012352
E -0.116773  1.901755  0.238127  1.996652  1.879879

In [163]:
# to actually drop it from the df
df.drop('new',axis=1,inplace=True)

In [164]:
df

W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [167]:
#Select a row
df.loc['A'] #returns the row with Label A

W    0.302665
X    1.693723
Y   -1.706086
Z   -1.159119
Name: A, dtype: float64

In [169]:
df.iloc[0] #using the index of the row

W    0.302665
X    1.693723
Y   -1.706086
Z   -1.159119
Name: A, dtype: float64

In [171]:
df.loc['B','Y'] #value at row B , column Y

0.16690463609281317

In [174]:
df.loc[['B','D'],['W','Z']]

W         Z
B -0.134841  0.184502
D -0.497104  0.484752

In [175]:
df > 0

W      X      Y      Z
A   True   True  False  False
B  False   True   True   True
C   True   True   True   True
D  False  False  False   True
E  False   True   True   True

In [176]:
df[df>0] #values where the condition is true

W         X         Y         Z
A  0.302665  1.693723       NaN       NaN
B       NaN  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D       NaN       NaN       NaN  0.484752
E       NaN  1.901755  0.238127  1.996652

In [177]:
df

W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [178]:
df['W'] > 0

A     True
B    False
C     True
D    False
E    False
Name: W, dtype: bool

In [181]:
df[df['W']> 0] #returns all the rows where df['W'] > 0

W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
C  0.807706  0.072960  0.638787  0.329646

In [182]:
df[df['Z']> 0]

W         X         Y         Z
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [183]:
df[df['Z']> 0]['Y'] #returns the Y column for the rows where df['Z']>0

B    0.166905
C    0.638787
D   -0.943406
E    0.238127
Name: Y, dtype: float64

In [185]:
df[df['Z']> 0] [['Y','X']]

Y         X
B  0.166905  0.390528
C  0.638787  0.072960
D -0.943406 -0.754070
E  0.238127  1.901755

In [187]:
#Passing in multiple conditions
df [ (df['Z']>0) & (df['X']>0)] #use & and not and !

W         X         Y         Z
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
E -0.116773  1.901755  0.238127  1.996652

In [191]:
df [ (df['Z']>0) | (df['X']>0)] #use | and not and !

W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [192]:
df.reset_index() #does not occur in place

index         W         X         Y         Z
0     A  0.302665  1.693723 -1.706086 -1.159119
1     B -0.134841  0.390528  0.166905  0.184502
2     C  0.807706  0.072960  0.638787  0.329646
3     D -0.497104 -0.754070 -0.943406  0.484752
4     E -0.116773  1.901755  0.238127  1.996652

In [194]:
newind = 'FR DE GB IT PL'.split()
newind

['FR', 'DE', 'GB', 'IT', 'PL']

In [202]:
df['countries'] = newind
df

W         X         Y         Z countries
A  0.302665  1.693723 -1.706086 -1.159119        FR
B -0.134841  0.390528  0.166905  0.184502        DE
C  0.807706  0.072960  0.638787  0.329646        GB
D -0.497104 -0.754070 -0.943406  0.484752        IT
E -0.116773  1.901755  0.238127  1.996652        PL

In [203]:
df.set_index('countries') #set the index to a column

W         X         Y         Z
countries                                        
FR         0.302665  1.693723 -1.706086 -1.159119
DE        -0.134841  0.390528  0.166905  0.184502
GB         0.807706  0.072960  0.638787  0.329646
IT        -0.497104 -0.754070 -0.943406  0.484752
PL        -0.116773  1.901755  0.238127  1.996652

MultiIndex

In [204]:
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [205]:
hier_index

MultiIndex(levels=[['G1', 'G2'], [1, 2, 3]],
           labels=[[0, 0, 0, 1, 1, 1], [0, 1, 2, 0, 1, 2]])

In [207]:
df = pd.DataFrame(np.random.randn(6,2),index=hier_index,columns=['A','B'])
df

A         B
G1 1  0.147027 -0.479448
   2  0.558769  1.024810
   3 -0.925874  1.862864
G2 1 -1.133817  0.610478
   2  0.386030  2.084019
   3 -0.376519  0.230336

In [208]:
df.loc['G1']

A         B
1  0.147027 -0.479448
2  0.558769  1.024810
3 -0.925874  1.862864

In [211]:
df.index.names = ['grp','num']

In [212]:
df

A         B
grp num                    
G1  1    0.147027 -0.479448
    2    0.558769  1.024810
    3   -0.925874  1.862864
G2  1   -1.133817  0.610478
    2    0.386030  2.084019
    3   -0.376519  0.230336

In [214]:
df.loc['G2'].loc[2].loc['B']

2.084018530338962

In [215]:
df.loc['G2'].loc[2]['B']

2.084018530338962

In [217]:
df.xs('G1')

A         B
num                    
1    0.147027 -0.479448
2    0.558769  1.024810
3   -0.925874  1.862864

In [218]:
df.xs(1,level='num') #returns values where num = 1

A         B
grp                    
G1   0.147027 -0.479448
G2  -1.133817  0.610478

### Pandas MissingData

In [219]:
import numpy as np
import pandas as pd

d = {'A':[1,2,np.nan],'B':[5,np.nan,np.nan],'C':[1,2,3]}

In [221]:

df = pd.DataFrame(d)
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [222]:
df.dropna() #any rows will be dropped

A    B  C
0  1.0  5.0  1

In [223]:
df.dropna(axis=1)

C
0  1
1  2
2  3

In [225]:
df.dropna(thresh=2) # Wwill not drop any row with at leaast 2 non empty values

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [226]:
df.fillna(value=0) #fills empty values with 0

A    B  C
0  1.0  5.0  1
1  2.0  0.0  2
2  0.0  0.0  3

In [228]:
df['A'].fillna(value = df['A'].mean()) #fills the missing value with the average of the column

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

### Pandas - Grouby

In [230]:
import pandas as pd
# Create dataframe
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,124,243,350]}

df = pd.DataFrame(data)
df

Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [232]:
bycomp = df.groupby('Company')
bycomp.mean()

Sales
Company       
FB       296.5
GOOG     160.0
MSFT     232.0

In [235]:
bycomp.sum().loc['FB']

Sales    593
Name: FB, dtype: int64

In [236]:
df.groupby('Company').mean().loc['MSFT']

Sales    232.0
Name: MSFT, dtype: float64

In [237]:
df.groupby('Company').count() #counts nb of instances by column

Person  Sales
Company               
FB            2      2
GOOG          2      2
MSFT          2      2

In [238]:
df.groupby('Company').describe()

Sales                                                        
        count   mean         std    min     25%    50%     75%    max
Company                                                              
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [239]:
df.groupby('Company').describe().transpose()

Company              FB        GOOG        MSFT
Sales count    2.000000    2.000000    2.000000
      mean   296.500000  160.000000  232.000000
      std     75.660426   56.568542  152.735065
      min    243.000000  120.000000  124.000000
      25%    269.750000  140.000000  178.000000
      50%    296.500000  160.000000  232.000000
      75%    323.250000  180.000000  286.000000
      max    350.000000  200.000000  340.000000

### Pandas - Merging 

In [ ]:
pd.concatenate([df1,df2]) #by rows
pd.concatenate([df1,df2],axis=1) #by columns

In [ ]:
pd.merge(df1left,df2right)

In [ ]:
df.join(right)

### Pandas - Operations

In [360]:
import numpy as np
import pandas as pd
df = pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['abc','def','ghi','xyz']})
df.head()

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [241]:
df['col2'].unique()

array([444, 555, 666], dtype=int64)

In [242]:
df['col2'].nunique() #nb f unique values

3

In [361]:
df['col2'].value_counts()

444    2
555    1
666    1
Name: col2, dtype: int64

In [245]:
def times2(x):
    return x*2

In [246]:
df['col1'].apply(times2)

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [248]:
df['col2'].apply(lambda x :x*2)

0     888
1    1110
2    1332
3     888
Name: col2, dtype: int64

In [250]:
df.drop('col1',axis=1)

col2 col3
0   444  abc
1   555  def
2   666  ghi
3   444  xyz

In [251]:
df.columns

Index(['col1', 'col2', 'col3'], dtype='object')

In [255]:
df.sort_values('col2')

col1  col2 col3
0     1   444  abc
3     4   444  xyz
1     2   555  def
2     3   666  ghi

In [256]:
df.isnull()

col1   col2   col3
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False

### Pandas input and output

In [258]:
import pandas as pd

In [259]:
pwd

'C:\\Users\\Rita\\Documents\\ML_with_Python'

In [285]:
df = pd.read_csv('example')

In [286]:
df

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [287]:
df.to_csv('output', index=False)

In [288]:
df = pd.read_csv('output')

In [289]:
df

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [294]:
dfex= pd.read_excel('Excel_Sample.xlsx',sheet_name='Sheet1')
dfex

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [296]:
dfex.to_excel('Excel_test2.xlsx',sheet_name='testing')

In [297]:
df = pd.read_html('http://www.fdic.gov/bank/individual/failed/banklist.html')

In [298]:
df

[                                             Bank Name                City  \
 0                  Washington Federal Bank for Savings             Chicago   
 1      The Farmers and Merchants State Bank of Argonia             Argonia   
 2                                  Fayette County Bank          Saint Elmo   
 3    Guaranty Bank, (d/b/a BestBank in Georgia & Mi...           Milwaukee   
 4                                       First NBC Bank         New Orleans   
 5                                        Proficio Bank  Cottonwood Heights   
 6                        Seaway Bank and Trust Company             Chicago   
 7                               Harvest Community Bank          Pennsville   
 8                                          Allied Bank            Mulberry   
 9                         The Woodbury Banking Company            Woodbury   
 10                              First CornerStone Bank     King of Prussia   
 11                                  Trust Company B

In [299]:
df[0]

Bank Name                City  \
0                  Washington Federal Bank for Savings             Chicago   
1      The Farmers and Merchants State Bank of Argonia             Argonia   
2                                  Fayette County Bank          Saint Elmo   
3    Guaranty Bank, (d/b/a BestBank in Georgia & Mi...           Milwaukee   
4                                       First NBC Bank         New Orleans   
5                                        Proficio Bank  Cottonwood Heights   
6                        Seaway Bank and Trust Company             Chicago   
7                               Harvest Community Bank          Pennsville   
8                                          Allied Bank            Mulberry   
9                         The Woodbury Banking Company            Woodbury   
10                              First CornerStone Bank     King of Prussia   
11                                  Trust Company Bank             Memphis   
12                          North Milwaukee State Bank           Milwaukee   
13                              Hometown National Bank            Longview   
14                                 The Bank of Georgia      Peachtree City   
15                                        Premier Bank              Denver   
16                                      Edgebrook Bank             Chicago   
17                              Doral Bank  En Espanol            San Juan   
18                   Capitol City Bank & Trust Company             Atlanta   
19                             Highland Community Bank             Chicago   
20                    First National Bank of Crestview           Crestview   
21                                  Northern Star Bank             Mankato   
22              Frontier Bank, FSB D/B/A El Paseo Bank         Palm Desert   
23               The National Republic Bank of Chicago             Chicago   
24                                      NBRS Financial          Rising Sun   
25                               GreenChoice Bank, fsb             Chicago   
26                            Eastside Commercial Bank             Conyers   
27                              The Freedom State Bank             Freedom   
28                                         Valley Bank     Fort Lauderdale   
29                                         Valley Bank              Moline   
..                                                 ...                 ...   
525                                  ANB Financial, NA         Bentonville   
526                                          Hume Bank                Hume   
527                             Douglass National Bank         Kansas City   
528                                  Miami Valley Bank            Lakeview   
529                                            NetBank          Alpharetta   
530                          Metropolitan Savings Bank          Pittsburgh   
531                                    Bank of Ephraim             Ephraim   
532                                      Reliance Bank        White Plains   
533              Guaranty National Bank of Tallahassee         Tallahassee   
534                                Dollar Savings Bank              Newark   
535                               Pulaski Savings Bank        Philadelphia   
536              First National Bank of Blanchardville      Blanchardville   
537                              Southern Pacific Bank            Torrance   
538                        Farmers Bank of Cheneyville         Cheneyville   
539                                      Bank of Alamo               Alamo   
540             AmTrade International Bank  En Espanol             Atlanta   
541                     Universal Federal Savings Bank             Chicago   
542                       Connecticut Bank of Commerce            Stamford   
543                                   New Century Bank     Shelby Township   
544                              Net 1st National Bank          Boc

In [300]:
##Pandas Exercises
import pandas as pd
#reading dataframe
sal = pd.read_csv('Salaries.csv')
sal.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

In [301]:
sal.info() #returns nb of entries

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
Id                  148654 non-null int64
EmployeeName        148654 non-null object
JobTitle            148654 non-null object
BasePay             148045 non-null float64
OvertimePay         148650 non-null float64
OtherPay            148650 non-null float64
Benefits            112491 non-null float64
TotalPay            148654 non-null float64
TotalPayBenefits    148654 non-null float64
Year                148654 non-null int64
Notes               0 non-null float64
Agency              148654 non-null object
Status              0 non-null float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [302]:
sal['BasePay'].mean() #average BasePay

66325.4488404877

In [303]:
sal['OvertimePay'].max() #Highest overtime Payed

245131.88

In [304]:
sal[sal['EmployeeName']=='JOSEPH DRISCOLL']['JobTitle']  #Job Title of dude Joseph

24    CAPTAIN, FIRE SUPPRESSION
Name: JobTitle, dtype: object

In [305]:
sal[sal['EmployeeName']=='JOSEPH DRISCOLL']['TotalPayBenefits']  #Total Money this guys makes

24    270324.91
Name: TotalPayBenefits, dtype: float64

In [306]:
sal[sal['TotalPayBenefits']==sal['TotalPayBenefits'].max()]['EmployeeName'] #Name of the highest paid prs

0    NATHANIEL FORD
Name: EmployeeName, dtype: object

In [307]:
sal[sal['TotalPayBenefits']== sal['TotalPayBenefits'].min()]  #all row , lowest paid pers

Id EmployeeName                    JobTitle  BasePay  OvertimePay  \
148653  148654    Joe Lopez  Counselor, Log Cabin Ranch      0.0          0.0   

        OtherPay  Benefits  TotalPay  TotalPayBenefits  Year  Notes  \
148653   -618.13       0.0   -618.13           -618.13  2014    NaN   

               Agency  Status  
148653  San Francisco     NaN

In [308]:
sal.groupby('Year').mean()['BasePay'] 

Year
2011    63595.956517
2012    65436.406857
2013    69630.030216
2014    66564.421924
Name: BasePay, dtype: float64

In [310]:
sal['JobTitle'].nunique()  #nb of unique jobs

2159

In [311]:
sal['JobTitle'].value_counts().head(5) #most common jobs

Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: JobTitle, dtype: int64

In [321]:
sal[sal['Year']== 2013]['JobTitle'].nunique() #this will return nb of unique jobs 

1051

In [325]:
sum(sal[sal['Year']==2013]['JobTitle'].value_counts() == 1) # this will return jobs that show up only once

202

In [327]:
#people with string chief in their title 
def chief_string(title):
    if 'chief' in title.lower():
        return True
    else:
        return False

In [328]:
sum(sal['JobTitle'].apply(lambda x: chief_string(x)))

627

In [330]:
import pandas as pd
ecom = pd.read_csv('Ecommerce Purchases')
ecom.head()

Address    Lot AM or PM  \
0  16629 Pace Camp Apt. 448\nAlexisborough, NE 77...  46 in       PM   
1  9374 Jasmine Spurs Suite 508\nSouth John, TN 8...  28 rn       PM   
2                   Unit 0065 Box 5052\nDPO AP 27450  94 vE       PM   
3              7780 Julia Fords\nNew Stacy, WA 45798  36 vm       PM   
4  23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...  20 IE       AM   

                                        Browser Info  \
0  Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...   
1  Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...   
2  Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...   
3  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...   
4  Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...   

                           Company       Credit Card CC Exp Date  \
0                  Martinez-Herman  6011929061123406       02/20   
1  Fletcher, Richards and Whitaker  3337758169645356       11/18   
2       Simpson, Williams and Pham      675957666125       08/19   
3  Williams, Marshall and Buchanan  6011578504430710       02/24   
4        Brown, Watson and Andrews  6011456623207998       10/25   

   CC Security Code                  CC Provider  \
0               900                 JCB 16 digit   
1               561                   Mastercard   
2               699                 JCB 16 digit   
3               384                     Discover   
4               678  Diners Club / Carte Blanche   

                            Email                                     Job  \
0               pdunlap@yahoo.com  Scientist, product/process development   
1              anthony41@reed.com                       Drilling engineer   
2  amymiller@morales-harrison.com                Customer service manager   
3     brent16@olson-robinson.info                       Drilling engineer   
4     christopherwright@gmail.com                             Fine artist   

        IP Address Language  Purchase Price  
0  149.146.147.205       el           98.14  
1     15.160.41.51       fr           70.73  
2   132.207.160.22       de            0.95  
3     30.250.74.19       es           78.04  
4     24.140.33.94       es           77.82

In [331]:
ecom.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
Address             10000 non-null object
Lot                 10000 non-null object
AM or PM            10000 non-null object
Browser Info        10000 non-null object
Company             10000 non-null object
Credit Card         10000 non-null int64
CC Exp Date         10000 non-null object
CC Security Code    10000 non-null int64
CC Provider         10000 non-null object
Email               10000 non-null object
Job                 10000 non-null object
IP Address          10000 non-null object
Language            10000 non-null object
Purchase Price      10000 non-null float64
dtypes: float64(1), int64(2), object(11)
memory usage: 1.1+ MB


In [333]:
ecom['Purchase Price'].mean() #average purchase price

50.347302

In [334]:
ecom['Purchase Price'].min()

0.0

In [335]:
ecom['Purchase Price'].max()

99.99

In [350]:
#people with english as language
ecom[ecom['Language'] == 'en'].count()

Address             10000
Lot                 10000
AM or PM            10000
Browser Info        10000
Company             10000
Credit Card         10000
CC Exp Date         10000
CC Security Code    10000
CC Provider         10000
Email               10000
Job                 10000
IP Address          10000
Language            10000
Purchase Price      10000
dtype: int64

In [353]:
ecom[ecom['Job']=='Lawyer'].count()

Address             30
Lot                 30
AM or PM            30
Browser Info        30
Company             30
Credit Card         30
CC Exp Date         30
CC Security Code    30
CC Provider         30
Email               30
Job                 30
IP Address          30
Language            30
Purchase Price      30
dtype: int64

In [355]:
ecom.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
Address             10000 non-null object
Lot                 10000 non-null object
AM or PM            10000 non-null object
Browser Info        10000 non-null object
Company             10000 non-null object
Credit Card         10000 non-null int64
CC Exp Date         10000 non-null object
CC Security Code    10000 non-null int64
CC Provider         10000 non-null object
Email               10000 non-null object
Job                 10000 non-null object
IP Address          10000 non-null object
Language            10000 non-null object
Purchase Price      10000 non-null float64
dtypes: float64(1), int64(2), object(11)
memory usage: 1.1+ MB


In [362]:
ecom['AM or PM'].value_counts()

PM    5068
AM    4932
Name: AM or PM, dtype: int64

In [365]:
#5 most common job titles
ecom['Job'].value_counts().head(5)

Interior and spatial designer        31
Lawyer                               30
Social researcher                    28
Research officer, political party    27
Purchasing manager                   27
Name: Job, dtype: int64

In [367]:
ecom[ecom['Lot']=='90 WT']['Purchase Price']

513    75.1
Name: Purchase Price, dtype: float64

In [369]:
ecom[ecom['Credit Card']==4926535242672853]['Email']

1234    bondellen@williams-garza.com
Name: Email, dtype: object

In [373]:
#counting people with American express and more than 95$ purchase
ecom[(ecom['CC Provider']=='American Express') & (ecom ['Purchase Price'] > 95)].count()

Address             39
Lot                 39
AM or PM            39
Browser Info        39
Company             39
Credit Card         39
CC Exp Date         39
CC Security Code    39
CC Provider         39
Email               39
Job                 39
IP Address          39
Language            39
Purchase Price      39
dtype: int64

In [382]:
#counting people who have credit card that expires in 2025
#sal['JobTitle'].apply(lambda x: chief_string(x))
def year_2025 (stringy):
    if '25' in stringy:
        return True
    else :
        return False
    
ecom[ecom['CC Exp Date'].apply(lambda x: year_2025(x))].count()

Address             1033
Lot                 1033
AM or PM            1033
Browser Info        1033
Company             1033
Credit Card         1033
CC Exp Date         1033
CC Security Code    1033
CC Provider         1033
Email               1033
Job                 1033
IP Address          1033
Language            1033
Purchase Price      1033
dtype: int64

In [391]:
#top 5 email providers
def split_email(email):
    return email.split('@')[1]

ecom['Email'].apply(lambda email : split_email(email)).value_counts()

hotmail.com                1638
yahoo.com                  1616
gmail.com                  1605
smith.com                    42
williams.com                 37
brown.com                    29
johnson.com                  29
jones.com                    25
davis.com                    25
martinez.com                 19
white.com                    15
martin.com                   15
thompson.com                 14
miller.com                   14
thomas.com                   14
rodriguez.com                14
garcia.com                   14
jackson.com                  14
hill.com                     13
harris.com                   12
taylor.com                   12
wilson.com                   11
walker.com                   11
moore.com                    11
long.com                     10
nelson.com                   10
hernandez.com                10
king.com                     10
anderson.com                 10
lee.com                      10
                           ... 
salinas.

In [380]:
ecom['CC Exp Date']

0       02/20
1       11/18
2       08/19
3       02/24
4       10/25
5       07/25
6       07/24
7       06/25
8       04/24
9       01/17
10      02/17
11      06/26
12      05/26
13      01/25
14      09/22
15      04/25
16      06/22
17      01/26
18      12/22
19      02/20
20      03/22
21      03/25
22      07/22
23      02/23
24      07/18
25      05/19
26      03/19
27      12/16
28      11/24
29      07/22
        ...  
9970    07/19
9971    01/21
9972    04/22
9973    02/19
9974    04/26
9975    01/19
9976    08/21
9977    06/21
9978    11/21
9979    10/23
9980    12/24
9981    01/19
9982    09/18
9983    04/23
9984    03/21
9985    08/21
9986    08/18
9987    12/24
9988    10/16
9989    12/23
9990    04/24
9991    02/24
9992    10/20
9993    10/25
9994    01/25
9995    03/22
9996    07/25
9997    05/21
9998    11/17
9999    02/19
Name: CC Exp Date, Length: 10000, dtype: object